### PR TITLE
Update to GHC 9.4

### PR DESCRIPTION
**Pull request by arcz**

### CODE REVIEW

**Comment by siraben** [comment]
`nix develop` fails on aarch64-darwin due to reference cycle in ormolu, part of haskell-language-server

```
error: cycle detected in build of '/nix/store/6v4rk8xbnzhxaxpnllbfvj5d4nhsrwy7-ormolu-0.5.3.0.drv' in the references of output 'bin' from output 'out'
```

**Comment by hellwolf** [comment]
ping this one, nixpkgs master also switched to ghc94

**Comment by hellwolf** [comment]
Fwiw, I created a patch in nixpkgs upstream to fix the build: https://github.com/NixOS/nixpkgs/pull/251919

**Comment by ggrieco-tob** [comment]
This looks ready to go, but it looks some builds are broken? @arcz

**Pull request merged**
