### PR TITLE
GitHub Actions: fix macOS build

### PR DESCRIPTION
**Pull request by elopez**
Currently the CI system fails on macOS with several errors related
to Homebrew and cache corruption. This implements temporal
workarounds for both issues. For more details, see:

 * https://github.com/actions/virtual-environments/issues/1811
 * https://github.com/actions/cache/issues/403

Closes: #525

### CODE REVIEW

**Comment by elopez** [comment]
Looks like there is a second issue here; if the macOS pipeline is run twice, it fails the second time with some strange error when trying to run Cabal. I thought it could be some older binaries on the cache, but it does not look like that's the case. I'll continue investigating soon.

**Comment by elopez** [comment]
I think this should be it now. Give it a pipeline rerun, just in case :smile:

**Comment by incertia** [comment]
on a personal level i just want to ignore anything macos related until github gets their shit together but this looks good

**Comment by ggrieco-tob** [comment]
macOS tests are temporarily disabled now, but we can use this PR for the fix, when we re-enabled them

**Comment by incertia** [comment]
seems like macOS builds are running fine now, is it ok if we close this?

**Comment by elopez** [comment]
yeah, this got merged through #527, closing then :smile:

**Pull request closed without merging**
