### PR TITLE
Fuzz tx.gasprice

### PR DESCRIPTION
**Pull request by arcz**
This is an attempt to solve https://github.com/crytic/echidna/issues/304. The test from the issue is included. I'm not entirely sure about the default for `maxGasprice`.

I didn't implement properly the `spliceTxs` part as the function is unused.

UI preview (examples/solidity/basic/gasprice.sol):
```
┌──────────Echidna──────────┐
│  echidna_state: failed!💥  │
│    Call sequence:         │
│      f() Gas price: 0x1   │
│                           │
└───────────────────────────┘
Campaign complete, C-c or esc to print report
```

### CODE REVIEW

**Comment by ggrieco-tob** [comment]
The code looks fine, but you include a bunch of stylistic changes that make the review more difficult than expected. Can we revert the unrelated changes?

**Comment by arcz** [comment]
@ggrieco-tob Sure, I've reduced the diff considerably. Hope it is easier to review now. I can put back the nonsemantic changes in a separate PR if that is desirable.

**Comment by ggrieco-tob** [comment]
It looks good now!, please make a separated PR with the style changes that you propose. Include a description of each one and why you think they are useful.

**Comment by ggrieco-tob** [comment]
Regarding `maxGasprice`, take a look to [here](https://ethgasstation.info/) to look for sensible values.

**Comment by arcz** [comment]
I've set 100 Gwei but it looks like half of this should be enough, or even less, what do you think?

**Pull request merged**
