### PR TITLE
RPC

### PR DESCRIPTION
**Pull request by arcz**
This is a very early RPC preview.

Set required config (the exact block number required for mint() in the example contract below to work):
`export ECHIDNA_RPC_BLOCK=15947726`
`export ECHIDNA_RPC_URL="https://eth-mainnet.alchemyapi.io/v2/<token>"`
Other providers, such as Infura should also work although I haven't tested it.

Check out this example contract: https://github.com/crytic/echidna/blob/d9e832c3464eb9478a7389cb535287e9a39344e2/tests/solidity/rpc/rpc.sol.

Running with `--format text` will print fetch queries (HTTP requests) as they happen that are not in the cache.
`echidna-test tests/solidity/rpc/rpc.sol --contract TestRPC --format text`

### CODE REVIEW

**Comment by arcz** [comment]
@rappie you might be interested in trying this out

**Comment by rappie** [comment]
Awesome, thanks! I'm definatly interested in this :)

I will do some tests soon.

**Comment by rappie** [comment]
I'm getting a segfault :disappointed: 

```
❯ echidna-test EchidnaForkTest.sol --contract TestRPC  --format text
Analyzing contract: /home/rappie/Desktop/echidna-fork-test/EchidnaForkTest.sol:TestRPC
<EVM.Query: fetch contract 0x4Ddc2D193948926D02f9B1fE9e1daa0718270ED5>
zsh: segmentation fault (core dumped)  echidna-test EchidnaForkTest.sol --contract TestRPC --format text
```

**Comment by rappie** [comment]
You can use `ganache` as a local RPC server to cache contract data and point `echidna` to it.

```shell
ganache --fork https://bsc-mainnet.nodereal.io/v1/<token>
export ECHIDNA_RPC_URL="http://127.0.0.1:8545/"
```
(mind the `http` without `s`)

**Pull request merged**
