### PR TITLE
Support the latest solc release

### PR DESCRIPTION
**Pull request by ggrieco-tob**
A simple PR to enable the use of newer solc version. It needs #209 to work (in the meantime, CI will fail).

### CODE REVIEW

**Comment by ESultanik** [comment]
You should also update the version installed in the `Dockerfile`.

**Comment by ggrieco-tob** [comment]
> You should also update the version installed in the `Dockerfile`.

Done. But you need to manually move the `/usr/bin/solc-0.5.7` binary to `/usr/bin/solc` (in the container) before calling echidna in Docker.

**Comment by ggrieco-tob** [comment]
I suspect HEVM 0.24 (the version currently used) does not support solc 0.5.7. I will experiment with #209 to confirm this..

**Comment by ggrieco-tob** [comment]
I just confirmed that this PR needs #209 to work as expected.

**Comment by aabdulwahed** [comment]
@ggrieco-tob Any updates regarding this issue ? Thanks

**Comment by ggrieco-tob** [comment]
@aabdulwahed This should work using hevm 0.29 (#209) . Can you test that PR please? :smiley:

**Comment by aabdulwahed** [comment]
After using the updates in #209 and changing the version to `0.5.6`, It works. I didn't try it for different solidity versions. Thanks @ggrieco-tob

**Pull request merged**
