### PR TITLE
Error on solc versions before 0.4.25

### PR DESCRIPTION
**Pull request by snd**
resolves https://github.com/crytic/echidna/issues/595

### CODE REVIEW

**Comment by ggrieco-tob** [comment]
If the user is using truffle or any other framework to compile, it is not necessary to have `solc` in the PATH. Is this PR handling that case correctly?

**Comment by snd** [comment]
Good point.
It's not handling that yet.
I'll look into handling it correctly.

**Comment by snd** [comment]
Seems that, when frameworks like truffle are used, then details like the solc version are abstracted away behind crytic-compile.
I've investigated this but found no clean way to get the solc version.
If `crytic-export/combined_solc.json` would contain the solc version this would be easy.
In my experiments it didn't.
@ggrieco-tob Any ideas?

**Comment by snd** [comment]
@montyly just had an idea for a solution: output the solc version used in the slither echidna printer. then check for it. going to implement this.

**Comment by snd** [comment]
superseded by https://github.com/crytic/echidna/pull/675

**Pull request closed without merging**
